from keras import layers, models

model = models.Sequential()
model.add(layers.Conv2D(3, (3, 3), activation="relu", data_format="channels_last", input_shape=(None, None, 3)))
model.add(layers.Dropout(0.2))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(3, (5, 5), activation="relu", padding="same"))
model.add(layers.Dropout(0.2))
model.add(layers.Conv2D(3, (3, 3), activation="relu", padding="same"))
model.add(layers.Dropout(0.2))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Flatten())
model.add(layers.Dense(500, activation="relu"))
model.add(layers.Dropout(0.2))
model.add(layers.Dense(500, activation="relu"))
model.add(layers.Dropout(0.2))
model.add(layers.Dense(500, activation="sigmoid"))
model.add(layers.Dropout(0.2))
model.summary()
